name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  code_quality:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Rubocop check
        run: gem install rubocop && rubocop
