name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "false"

      - name: Install bundle gem
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test

  code_quality:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Rubocop check
        run: gem install rubocop && rubocop
